config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:destroy] do
    resources :posts, only: [:index]
  end

  resources :comments, only: [:create, :show]

  resources :posts, only: [:new, :show, :edit, :update, :destroy, :create] do
    resources :comments, only: [:new]
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :child_comments,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: :Comment
  belongs_to :parent,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: :Comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :subs,
  through: :post_subs,
  source: :sub

  belongs_to :author,
    class_name: :User,
    foreign_key: :user_id,
    primary_key: :id

  has_many :post_subs,
    foreign_key: :post_id,
    primary_key: :id,
    class_name: :PostSub

  has_many :comments, as: :commentable

end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post_id, :sub_id, presence: true

  belongs_to :post,
  foreign_key: :post_id,
  primary_key: :id,
  class_name: :Post

  belongs_to :sub,
  foreign_key: :sub_id,
  primary_key: :id,
  class_name: :Sub



end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true

  belongs_to :user,
    class_name: :User,
    foreign_key: :user_id,
    primary_key: :id


  has_many :post_subs,
    foreign_key: :sub_id,
    primary_key: :id,
    class_name: :PostSub

  has_many :posts,
  through: :post_subs,
  source: :post
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 2, allow_nil: true}

  has_many :subs,
    foreign_key: :user_id,
    primary_key: :id,
    class_name: :Sub

  has_many :posts,
    foreign_key: :post_id,
    primary_key: :id,
    class_name: :Post

  has_many :comments, as: :commentable

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)

    return @user if @user && @user.is_password?(password)
    nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def login_user(user)
    session[:session_token] = user.session_token
    redirect_to subs_url
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    unless params[:comment_id].empty?
      @comment.commentable_id = params[:comment_id]
      @comment.commentable_type = "Comment"
      @comment.parent_comment_id = params[:comment_id]
    else
      @comment.commentable_id = params[:post_id]
      @comment.commentable_type = "Post"
      @comment.parent_comment_id = nil
    end

    if @comment.save
      if @comment.commentable_type == "Comment"
        # comment = @comment
        # until comment.parent_comment_id.nil?
        #   comment = Comment.find(comment.parent_comment_id)
        # end
        # redirect_to post_url(Post.find(comment.commentable_id))
        redirect_to post_url(Post.find(@comment.parent.commentable_id))
      else
        redirect_to post_url(Post.find(@comment.commentable_id))
      end
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :author?, only: [:edit, :update]

  def new
    @post = Post.new
    #@sub = Sub.find(post_params[:sub_id])
    render :new
  end

  def edit
    @post = Post.find(params[:id])
    # @sub = @post.sub
    render :edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      params[:post][:sub_ids].each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id)
      end


      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @sub = @post.sub
    @post.destroy
    redirect_to sub_url(@sub)
  end

  def index
    @posts = Sub.find(params[:id]).posts
    render :index
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids)
  end

  def author?
    @post = Post.find(params[:id])
    if current_user.id != @post.user_id
      redirect_to sub_url(Sub.find(@post.sub_id))
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



  def new
    @user = User.new
    render :new
  end
  def create
    @user = User.find_by_credentials(params[:user][:email],
    params[:user][:password])
    if @user.nil?
      @user = User.new
      render :new
    else
      login_user(@user)
    end

  end

  def destroy
    if current_user
      logout
    end
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_moderator_is_current_user, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.update_attributes(sub_params)

    if @sub.save
      redirect_to sub_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def ensure_moderator_is_current_user
    @sub = Sub.find(params[:id])
    if @sub.user_id == current_user.id
      return true
    else
      redirect_to sub_url(@sub)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <% unless post.nil? %>
    <input type="hidden" name="post_id" value="<%= post.id %>">
  <% end %>

  <% unless comment.nil? %>
    <input type="hidden" name="comment_id" value="<%= comment.id %>">
  <% end %>
  <textarea name="comment[content]" rows="8" cols="40">Content</textarea>
  <br>
  <input type="submit" value="Create Comment">
</form>

app/views/comments/new.html.erb
<h1>Create Comment for <%= @post.title %></h1>

<%= render "form", comment: @comment, post: @post %>

app/views/comments/show.html.erb
<h1><%= @comment.content %></h1>

<p>
  Reply
</p>
<%= render "form", comment: @comment, post: @post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= current_user.email unless current_user.nil? %>

<%= yield %>

  <% unless current_user.nil? %>
    <%= button_to "Logout", "/session", method: :delete %>
  <% end %>
</body>
</html>

app/views/posts/_form.html.erb
<% if post.persisted? %>
  <% url, method, button_text = post_url(post), "patch", "update post"%>
<% else %>
  <% url, method, button_text = posts_url, "post", "create post"%>
<% end %>

<form action="<%= url %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">


  <br>
  <label for="post_title">Title</label>
  <input type="text" name="post[title]" value="<%= post.title %>">
  <br>
  <label for="post_url">url</label>
  <input type="text" name="post[url]" value="<%= post.url %>">
  <br>
  <label for="post_content">Content</label>
  <textarea name="post[content]" rows="8" cols="40" id= "post_content"></textarea>
  <br>

  <% Sub.all.each do |sub| %>
  <input type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>" <%= checked = "checked" if post.sub_ids.include?(sub.id) %>> <%=sub.title%><br>
  <% end %>

  <br>

  <input type="submit" value="<%= button_text %>">

</form>

app/views/posts/_post.html.erb
<ul>
  <li>URL : <%= post.url %> </li>
  <li>Content : <%= post.content %> </li>
  <li>Author : <%= User.find(post.user_id).email %> </li>
</ul>

<label for="subs">Post belongs to subs :</label>
<ul id= "subs">
  <% post.subs.each do |sub| %>
    <li><%= sub.title %></li>
  <% end %>
</ul>


<%= button_to "Edit post", edit_post_url(post), method: :get %>
<br>

<label for="comments">COMMENTS:</label>
<ul id= "comments">
  <% post.comments.where(parent_comment_id: nil).each do |comment| %>
    <li><%= link_to comment.content, comment_url(comment) %></li>
      <ul>
        <% comment.child_comments.each do |child| %>
          <li> <%= child.content %> </li>
        <% end %>
      </ul>
  <% end %>
</ul>
<br>

<%= button_to "Create Comment", new_post_comment_url(post), method: :get %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form", post: @post, sub: @sub %>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<%= render "form", sub: @sub, post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= render "post", post: @post %>

app/views/subs/_form.html.erb
<% if sub.persisted? %>
  <% url, method, button_text = sub_url(sub), "patch", "update sub"%>
<% else %>
  <% url, method, button_text = subs_url, "post", "create sub"%>
<% end %>

<form action="<%= url %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <br>
  <label for="sub_title">Title</label>
  <input type="text" name="sub[title]" value="<%= sub.title %>">
  <br>
  <label for="sub_description">Description</label>
  <input type="text" name="sub[description]" value="<%= sub.description %>">
  <br>
  <input type="submit" value="<%= button_text %>">

</form>

app/views/subs/_sub.html.erb
<h2> <%= sub.description %>  </h2>

<label for="add_post"></label>
<form action="<%=new_post_url%>" method="get" id= "add_post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <input type="hidden" name="post[sub_id]" value="<%= sub.id %>">
  <input type="submit" value="Create Post">
</form>

app/views/subs/edit.html.erb
<h1>Edit sub</h1>


<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<% @subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub) %>
  <br>
  <br>
<% end %>

app/views/subs/new.html.erb
<h1>Create Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>

<%= render "sub", sub: @sub %>
<br>
<%= button_to "edit sub", edit_sub_url(@sub), method: :get%>

<br>

<% @sub.posts.each do |post| %>
  <%= link_to post.title, post_url(post) %>
  <br>
<% end %>

app/views/users/_form.html.erb
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="user_email">Email</label>
  <input type="text" name="user[email]" value="<%=user.email%>" id= "user_email">
  <br><br>
  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id= "user_password">
  <br><br>
  <input type="submit" value="Sign Up !">
</form>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render "form", user: @user %>